ticketee/config/routes.rb
Ticketee::Application.routes.draw do


  # the :controllers opt tells Devise you want to customize the controllers it uses
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  # addressing the promblem and defining a route for 
  get '/awaiting_confirmation', :to => "users#confirmation", :as => 'confirm_user'
  
  root :to => "projects#index"
  resources :projects do
    resources :tickets
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end
  
  put '/admin/users/:user_id/permissions',
  :to => 'admin/permissions#update',
  :as => :update_user_permissions
  
end

ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user # belongs_to method defines methods for accessing the association (like has_many)
  validates :title, :presence => true
  validates :description, :presence => true,
                          :length => { :minimum => 10 }
                          
end

ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # if it fails the others before_filters will not run (save CPU cycles)
  before_filter :authenticate_user! #, :except => [:index, :show]
  before_filter :find_project
  before_filter :find_ticket, :only => [:show,:edit,:update,:destroy]
  before_filter :authorize_create!, :only => [:new, :create]
  before_filter :authorize_update!, :only => [:edit, :update]
  before_filter :authorize_delete!, :only => :destroy

  def new
    @ticket = @project.tickets.build
  end
  
  def create
    # the merge! method is a Hash and HashWithIndifferentAccess method 
    #wich merges the provide keys and overrides any keys already specified.
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      # specify an Array containing a project obj and a ticket obj (project_ticket_path(@project,@ticket))
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end
  
  def show
    
  end
  
  def edit
    # empty because the find_ticket before filter does all the hard lifting
  end
  
  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
      
    else
      flash[:alert] = "Ticket has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @ticket.destroy 
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
    
  end
  
  def authorize_create!
    if !current_user.admin? && cannot?("create tickets".to_sym, @project)
      flash[:alert] = "You cannot create tickets on this project."
      redirect_to @project
    end
    
  end
  
  def authorize_update!
    if !current_user.admin? && cannot?(:"edit tickets", @project)
      flash[:alert] = "You cannot edit tickets on this project."
      redirect_to @project
    end
    
  end
  
  def authorize_delete!
    if !current_user.admin? && cannot?(:"delete tickets", @project)
      flash[:alert] = "You cannot delete tickets from this project."
      redirect_to @project
    end
    
  end
  

  private
   
    def find_project
      @project = Project.for(current_user).find(params[:project_id])
      # it will retrieve a Project only if the current_user has permission to view
      # that project or an admin, otherwise an ActiveRecord exception will be thrown and rescued 
      # here showing the users a message.
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to root_path
    end
    
    def find_ticket
      @ticket = @project.tickets.find(params[:id])
    end
end

ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
end

ticketee/app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>

<% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
		
	</p>
	<p>
		<%= f. label :description %><br>
		<%= f.text_area :description %>
	</p>
	<%= f.submit %>
	
<% end %>

ticketee/app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<!-- Re-using the form created with the form_for -->
<%= render "form" %>

ticketee/app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

ticketee/app/views/tickets/show.html.erb
<div id='ticket'>
	<br><small>Created by <%= @ticket.user.email %> </small>
	<h2><%= @ticket.title %></h2>
	
	<!-- Array argument passed to the link_to method (edit_project_ticket_path)-->
	<%= authorized?("edit tickets", @project) do %>
		<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
	<% end %>
	
  
  <%= authorized?("delete tickets", @project) do %>
	  <%= link_to "Delete Ticket", [@project, @ticket],
	     :method => :delete, 
       :confirm => "Are you sure you want to delete this ticket?" %>
	<% end %>


	<!-- The method simple_format converts the line breaks entered into the description field into HTMl break tags <br> -->
	<%= simple_format(@ticket.description) %>
</div>