ticketee/config/routes.rb
Ticketee::Application.routes.draw do


  # the :controllers opt tells Devise you want to customize the controllers it uses
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  # addressing the promblem and defining a route for 
  get '/awaiting_confirmation', :to => "users#confirmation", :as => 'confirm_user'
  
  root :to => "projects#index"
  resources :projects do
    resources :tickets
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end
  
  put '/admin/users/:user_id/permissions',
  :to => 'admin/permissions#update',
  :as => :update_user_permissions
  
end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :tickets, :dependent => :nullify # UPDATE tickets SET project_id = NULL 
                                            # WHERE project_id = :project_id
  # for large amount of tickets and DONT have callbacks use this:
  # :destroy_all # SQL - DELETE FROM tickets WHERE project_id = :project_id
  validates :name, :presence => true # Validations
  
  has_many :permissions, :as => :thing
  
  # usually the scope passin a block (lambda).
  # in this case the scope is dynamic according to which user is passed to it
  #the joins method uses a SQL INNER JOIN
  scope :readable_by, lambda { |user| 
    joins(:permissions).where(:permissions => { :action => "view",
                                                :user_id => user.id })}
                                                
  def self.for(user)
    # ternary statement, it substitute if/else
    user.admin? ? Project : Project.readable_by(user)
  end
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only =>[:index, :show]
  
  # before filter are run before all the actions in the controller unless you specify (:only,:exept)
  # find_project method sets up the @ project variable for you so no need for the:
  # @project = Project.find(params[:id]) in these methods anymore.
  before_filter :find_project, :only => [:show,:edit,:update,:destroy]

  def index
    # by calling all on the Project model we retriece all the records from the db as Project objects
    # and they are available as an Array-like object ( therefore passing the test and defining the
    # variable to the index.html.erb )
      @projects = Project.for(current_user).all
  end
  
  def new
    # Project constant is going to be a class located at models (thereby making it a model)
    @project = Project.new 
  end
  
  def create
    # hashWithIndifferenceAccess ( can reference a String key by using a matching symbol and vice-versa)    
    @project = Project.new(params[:project]) #to access the name field use params[:project][:name]

    if @project.save # saves the new object into projects table
      
      flash[:notice] = "Project has been created."
      #redirect_to method takes either a path or object to redirect to as a String (project_path(@project))
      redirect_to @project
    else
      flash[:alert] = "Project has not been created." 
      render :action =>"new"
    end
  end
  
  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    # update_attributes takes a hash of attributes identical to the ones passed to new or create, udates
    # those specified attributes on the object, and then saves them to the databse if they are valid
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else 
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy 
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end
  
  private
    def find_project
      #passing the params[:id] which gives a singleProject object that relates to a record in the database
      # the readable_by method returns a scope of only the projects the user is allowed to view
      @project = Project.for(current_user).find(params[:id]) # defined in model self.for
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
		
	</p>
	<%= f.submit %>
	
<% end %>	

ticketee/app/views/projects/edit.html.erb
<h2>Edit project</h2>

<!-- When a string is passed to the render method, Rails looks up a partial in the current directory matching the string and renders that instead -->
<%= render "form" %>
<%= link_to "Update Project", project_path(@project) %>

ticketee/app/views/projects/index.html.erb
<%= admins_only do %>
<%= link_to "New Project", new_project_path %>
<% end %>

<!-- %= link_to "Sign out", destroy_user_session_path, :method => :delete %-->

<h2>Projects</h2>
<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project %>
		</li>
	<% end %>
</ul>
		

ticketee/app/views/projects/new.html.erb
<h2>New project</h2>
<%= render "form" %>

ticketee/app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<!--<% title(@project.name, "Projects") %>-->
<title>
	<% if content_for?(:title) %>
		<%= yield(:title)%>
		<% else %>
			Ticketee
		<% end %>
</title>
<%= admins_only do%>
	<!-- Updating Project -->
	<%= link_to "Edit Project", edit_project_path(@project) %>

	<!-- Deleting Project -->
	<!-- :method tells Rails which HTTP method this link should be using -->
	<!-- By using DELETE instead of destroy, we protect an important route for our controller by ensuring that we have to follow the link from the site to make the proper request to delete this resource-->
	<!-- The confirm method prompt, using JavaScript, a confirmation message -->
	<%= link_to "Delete Project", @project, :method=> :delete, 
	:confirm => "Are you sure you want to delete this project?" %>
<% end %>

<%= authorized?("create tickets".to_sym, @project) do %>
	<%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

<ul id'tickets'>
	<% @project.tickets.each do |ticket| %>
		<li>
			#<%= ticket.id %>
	<%= link_to ticket.title, [@project, ticket] %>
		</li>
	<% end %>
</ul>