ticketee/config/routes.rb
Ticketee::Application.routes.draw do


  # the :controllers opt tells Devise you want to customize the controllers it uses
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  # addressing the promblem and defining a route for 
  get '/awaiting_confirmation', :to => "users#confirmation", :as => 'confirm_user'
  
  root :to => "projects#index"
  resources :projects do
    resources :tickets
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end
  
  put '/admin/users/:user_id/permissions',
  :to => 'admin/permissions#update',
  :as => :update_user_permissions
  
end

ticketee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> <!--sets to HTLML-->
<head>
  <title><%= @title || "Ticketee" %></title>
  <!--This is for including stylesheets -->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %> <!--This is for protecting the forms from cross-site request forgery (csrf) -->
</head>

<body>
<!--This code below renders all the 'flash' msgs that get defined (regardless of their name) and displays the notice set up in the controller -->
<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>
<% end %>
			
<h1><%= link_to "Ticketee", root_path %></h1>
<divid='nav'>
<nav>
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path %>
	<% end %>
	<br>
	<%= link_to "Sign in", new_user_session_path %>
	<%= admins_only do %>
		<%= link_to "Admin", admin_root_path %><br>
	<% end %>
</nav>

<%= yield %> 

</body>
</html>